CREATE TABLE dbo.amar_gathering
(
    [UID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ActionName VARCHAR(150) NOT NULL,
    ActionNameQuantityMin INT,
    ActionName1QuantityMax INT,
    SubActionName1 VARCHAR(150),
    SubActionName1QuantityMin INT,
    SubActionName1QuantityMax INT,
    SubActionName2 VARCHAR(150),
    SubActionName2QuantityMin INT,
    SubActionName2QuantityMax INT,
    SubActionName3 VARCHAR(150),
    SubActionName3QuantityMin INT,
    SubActionName3QuantityMax INT,
    SubActionName4 VARCHAR(150),
    SubActionName4QuantityMin INT,
    SubActionName4QuantityMax INT,
    SubActionName5 VARCHAR(150),
    SubActionName5QuantityMin INT,
    SubActionName5QuantityMax INT,
    [Level] INT NOT NULL,
    XP INT NOT NULL,
    RandomDropName1 VARCHAR(150),
    RandomDropNumberMin INT,
    RandomDropNumberMax INT,
    RequiredItem1Name VARCHAR(150),
    RequiredItem1 INT,
    RequiredItem2Name VARCHAR(150),
    RequiredItem2 INT
);
