CREATE TABLE dbo.amar_speed
(
    [UID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ActionName VARCHAR(150) NOT NULL,
    DropName1 VARCHAR(150),
    Drop1QuantityMin INT,
    Drop1QuantityMax INT,
    DropName2 VARCHAR(150),
    Drop2QuantityMin INT,
    Drop2QuantityMax INT,
    DropName3 VARCHAR(150),
    Drop3QuantityMin INT,
    Drop3QuantityMax INT,
    DropName4 VARCHAR(150),
    Drop4QuantityMin INT,
    Drop4QuantityMax INT,
    DropName5 VARCHAR(150),
    Drop5QuantityMin INT,
    Drop5QuantityMax INT,
    DropName6 VARCHAR(150),
    Drop6QuantityMin INT,
    Drop6QuantityMax INT,
    DropName7 VARCHAR(150),
    Drop7QuantityMin INT,
    Drop7QuantityMax INT,
    [Level] INT NOT NULL,
    XP INT NOT NULL,
    RandomDropName VARCHAR(150),
    RandomDropNumberMin INT,
    RandomDropNumberMax INT,
    RequiredItemName VARCHAR(150),
    RequiredItemNumber INT
);
