CREATE TABLE dbo.amar_cooking
(
    [UID] INT NOT NULL PRIMARY KEY,
    ActionName VARCHAR(150) NOT NULL,
    ActionNameQuantityMin INT,
    ActionNameQuantityMax INT,
    [Level] INT NOT NULL,
    XP INT NOT NULL,
    RandomDropName1 VARCHAR(150),
    RandomDropNumberMin INT,
    RandomDropNumberMax INT,
    RequiredItem1Name VARCHAR(150),
    RequiredItem1 INT,
    RequiredItem2Name VARCHAR(150),
    RequiredItem2 INT,
    RequiredItem3Name VARCHAR(150),
    RequiredItem3 INT,
    RequiredItem4Name VARCHAR(150),
    RequiredItem4 INT,
    RequiredItem5Name VARCHAR(150),
    RequiredItem5 INT,
    RequiredItem6Name VARCHAR(150),
    RequiredItem6 INT,
    RequiredItem7Name VARCHAR(150),
    RequiredItem7 INT,
    RequiredItem8Name VARCHAR(150),
    RequiredItem8 INT,
    RequiredItem9Name VARCHAR(150),
    RequiredItem9 INT,
    RequiredItem10Name VARCHAR(150),
    RequiredItem10 INT
);
