CREATE TABLE dbo.amar_alchemy
(
    [UID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ActionName VARCHAR(150) NOT NULL,
    ActionNameQuantityMin INT,
    ActionNameQuantityMax INT,
    [Level] INT NOT NULL,
    XP INT NOT NULL,
    RandomDropName1 VARCHAR(150),
    RandomDropNumber1 INT,
    RandomDropName2 VARCHAR(150),
    RandomDropName2Int INT
    RandomDropName3 VARCHAR(150),
    RandomDropName3Int INT,
    PumpkinRandomMin INT,
    PumpkinRandomMax INT,
    LemmingRandomMin INT,
    LemmingRandomMax INT,
    RequiredItem1Name VARCHAR(150),
    RequiredItem1 INT,
    RequiredItem2Name VARCHAR(150),
    RequiredItem2,
    RequiredItem3Name VARCHAR(150),
    RequiredItem3 INT,
    RequiredItem4Name VARCHAR(150),
    RequiredItem4 INT,
    RequiredItem5Name VARCHAR(150),
    RequiredItem5 INT,
    RequiredItem6Name VARCHAR(150),
    RequiredItem6 INT,
    RequiredItem7Name VARCHAR(150),
    RequiredItem7 INT,
    RequiredItem8Name VARCHAR(150),
    RequiredItem8 INT
);
