INSERT INTO
    dbo.amarcombat (
        [UID],
        ActionName,
        RequiredItemName,
        RequiredItemQTY,
        [Level],
        XP,
        MOB1,
        MOB1DROP1,
        MOB1DROP1MIN,
        MOB1DROP1MAX,
        MOB1DROP2,
        MOB1DROP2MIN,
        MOB1DROP2MAX,
        MOB1DROP3,
        MOB1DROP3MIN,
        MOB1DROP3MAX,
        MOB1DROP4,
        MOBDROP4MIN,
        MOBDROP4MAX,
        MOB2,
        MOB2DROP1,
        MOB2DROP1MIN,
        MOB2DROP1MAX,
        MOB2DROP2,
        MOB2DROP2MIN,
        MOB2DROP2MAX,
        MOB2DROP3,
        MOB2DROP3MIN,
        MOB2DROP3MAX,
        MOB2DROP4,
        MOB2DROP4MIN,
        MOB2DROP4MAX,
        MOB3,
        MOB3DROP1,
        MOB3DROP1MIN,
        MOB3DROP1MAX,
        MOB3DROP2,
        MOB3DROP2MIN,
        MOB3DROP2MAX,
        MOB3DROP3,
        MOB3DROP3MIN,
        MOB3DROP3MAX,
        MOB3DROP4,
        MOB3DROP4MIN,
        MOB3DROP4MAX,
        MOB4,
        MOB4DROP1,
        MOB4DROP1MIN,
        MOB4DROP1MAX,
        MOB4DROP2,
        MOB4DROP2MIN,
        MOB4DROP2MAX,
        MOB4DROP3,
        MOB4DROP3MIN,
        MOB4DROP3MAX,
        MOB4DROP4,
        MOB4DROP4MIN,
        MOB4DROP4MAX
    )
VALUES
    (
        1,
        'Hunt Forest Critters Tier 1',
        NULL,
        NULL,
        1,
        10,
        'Spotted Owl',
        'Animal Hides',
        1,
        1,
        'Feathers',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Rabbit',
        'Animal Hides',
        1,
        1,
        'Raw Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        2,
        'Hunt Forest Critters Tier 2',
        NULL,
        NULL,
        5,
        12,
        'Spotted Owl',
        'Animal Hides',
        1,
        1,
        'Feathers',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Rabbit',
        'Animal Hides',
        1,
        1,
        'Raw Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Boar',
        'Animal Hides',
        1,
        2,
        'Raw Meat',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        3,
        'Hunt Wild Game Tier 1',
        NULL,
        NULL,
        10,
        16,
        'Grey Wolf',
        'Animal Hides',
        1,
        1,
        'Raw Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bull Moose',
        'Animal Hides',
        1,
        1,
        'Raw Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        4,
        'Hunt Wild Game Tier 2',
        NULL,
        NULL,
        15,
        20,
        'Grey Wolf',
        'Animal Hides',
        1,
        1,
        'Raw Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bull Moose',
        'Animal Hides',
        1,
        1,
        'Raw Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Grizzly Bear',
        'Animal Hides',
        1,
        2,
        'Raw Meat',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        5,
        'Graveyard',
        NULL,
        NULL,
        15,
        20,
        'Skelton',
        'Bones',
        1,
        3,
        'Tattered Cloth',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Spectre',
        'Ectoplasm',
        1,
        2,
        'Tattered Cloth',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Banshee',
        'Ectoplasm',
        1,
        3,
        'Tattered Cloth',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Ghoul',
        'Bones',
        1,
        2,
        'Tattered Cloth',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        6,
        'Graveyard Dungeons',
        NULL,
        NULL,
        25,
        20,
        'Skelton King',
        'Skeletal Blades',
        1,
        1,
        'Undead Tree Limbs',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Spectral Warlord',
        'Spectral Bowstrings',
        1,
        1,
        'Spectral Hilts',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Banshee Queen',
        'Banshees Warp',
        1,
        1,
        'Twisted Roots',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7,
        'Hunt Snakes Tier 1',
        NULL,
        NULL,
        20,
        22,
        'Boa Constrictor',
        'Snake Hides',
        1,
        2,
        'Snake Meat',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Green Tree Snake',
        'Snake Hides',
        1,
        1,
        'Snake Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        8,
        'Hunt Snakes Tier 2',
        NULL,
        NULL,
        30,
        28,
        'Green Tree Snake',
        'Snake Hides',
        1,
        1,
        'Snake Meat',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Anaconda',
        'Snake Hides',
        1,
        3,
        'Snake Meat',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Rainbow Python',
        'Snake Hides',
        1,
        1,
        'Snake Meat',
        1,
        2,
        'Chromatic Scales',
        1,
        10,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        9,
        'Merfolk',
        NULL,
        NULL,
        35,
        32,
        'Merfolk Soldier',
        'Seaweed',
        1,
        2,
        'Pearls',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Merfolk Sharpshooter',
        'Seaweed',
        1,
        2,
        'Pearls',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Merfolk Hydromancer',
        'Seaweed',
        1,
        3,
        'Pearls',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        10,
        'Merfolk Dungeon',
        NULL,
        NULL,
        45,
        32,
        'Merfolk Marauder',
        'Pearlescent Shards',
        1,
        1,
        'Tarnished Hilts',
        1,
        1,
        'Salt Stones',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Merfolk Quartermaster',
        'Pearlescent Shards',
        1,
        1,
        'Splintered Bows',
        1,
        1,
        'Shattered Merfolk',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Merfolk Archmage',
        'Pearlescent Shards',
        1,
        1,
        'Driftwood',
        1,
        1,
        'Knotted Rope',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        11,
        'Hunt Secluded Game',
        'Sip of Rum',
        1,
        30,
        20,
        'Auroch',
        'Auroch Hides',
        1,
        1,
        'Auroch Horns',
        1,
        1,
        'Catguts',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Tarpan',
        'Tarpan Skulls',
        1,
        1,
        'Tarpan Hairs',
        5,
        10,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Giant Tortoise',
        'Tortoise Eggs',
        1,
        3,
        'Tortoise Shells',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        12,
        'Hunt Arctic Game Tier 1',
        NULL,
        NULL,
        40,
        34,
        'Arctic Fox',
        'Snow Furs',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Caribou',
        'Snow Furs',
        2,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Muskox',
        'Snow Furs',
        2,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        13,
        'Hunt Arctic Game Tier 2',
        NULL,
        NULL,
        50,
        42,
        'Caribou',
        'Snow Furs',
        2,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Muskox',
        'Snow Furs',
        2,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Polar Bear',
        'Snow Furs',
        2,
        4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        14,
        'Frozen Cavern',
        NULL,
        NULL,
        55,
        46,
        'Frost Giant',
        'Frigid Fabric',
        1,
        2,
        'Ice Needles',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Yeti',
        'Qiviut',
        1,
        2,
        'Larch Leaves',
        1,
        3,
        'Bearberry Leaves',
        1,
        2,
        NULL,
        NULL,
        NULL,
        'Ettin',
        'Frigid Fabric',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Tundra Titan',
        'Frigid Fabric',
        1,
        3,
        'Ice Needles',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        15,
        'Frozen Dungeon',
        NULL,
        NULL,
        65,
        46,
        'Tundra Hersir',
        'Glacial Shards',
        1,
        1,
        'Titans Blade',
        1,
        1,
        'Icy Bows',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Dire Yeti',
        'Glacial Shards',
        1,
        1,
        'Ice Crystal',
        1,
        1,
        'Sinew of the Yeti',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Ettin Warlord',
        'Glacial Shards',
        1,
        1,
        'Shattered Hilts',
        1,
        1,
        'Frozen Branch',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        16,
        'Sea Ice',
        NULL,
        NULL,
        60,
        36,
        'Narwhal',
        'Narwhal Tusks',
        1,
        1,
        'Muktuk',
        1,
        1,
        'Narwhal Meat',
        1,
        3,
        'Narwhal Bones',
        1,
        1,
        'Ringed Seal',
        'Seal Meat',
        1,
        1,
        'Seal Skin',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Walrus',
        'Walrus Meat',
        1,
        2,
        'Walrus Furs',
        1,
        2,
        'Walrus Tusks',
        1,
        2,
        'Walrus Skulls',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        17,
        'Hunt Swamp Critters Tier 1',
        NULL,
        NULL,
        60,
        48,
        'Jevenile Alligator',
        'Alligator Meat',
        1,
        2,
        'Swamp Hides',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Giant Toad',
        'Toad Meat',
        1,
        3,
        'Toad Skins',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Giant Newt',
        'Newt Eyes',
        2,
        2,
        'Newt Skins',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        18,
        'Hunt Swamp Critters Tier 2',
        NULL,
        NULL,
        70,
        54,
        'Giant Toad',
        'Toad Meat',
        1,
        3,
        'Toad Skins',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Jevenile Alligator',
        'Alligator Meat',
        1,
        2,
        'Swamp Hides',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Adult Alligator',
        'Alligator Meat',
        2,
        3,
        'Swamp Hides',
        2,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        19,
        'Scorched Grotto',
        NULL,
        NULL,
        75,
        58,
        'Fire Imp',
        'Imp Wings',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Fire Salamander',
        'Charred Fabric',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Flame Giant',
        'Charred Fabric',
        1,
        3,
        'Living Flames',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Ember Golem',
        'Charred Fabric',
        1,
        2,
        'Glowing Embers',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        20,
        'Scorched Dungeon',
        NULL,
        NULL,
        85,
        58,
        'Immolated Golem',
        'Ember Shards',
        1,
        1,
        'Fiery Bows',
        1,
        1,
        'Ember Blades',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'King of Flames',
        'Ember Shards',
        1,
        1,
        'Fire Crystal',
        1,
        1,
        'Charred Hilts',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Queen of Flames',
        'Ember Shards',
        1,
        1,
        'Singed Ropes',
        1,
        1,
        'Scorched Tree Limbs',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        21,
        'Hunt Desert Critters Tier 1',
        NULL,
        NULL,
        80,
        60,
        'Monitor',
        'Desert Hides',
        1,
        2,
        'Monitor Scales',
        1,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Ostrich',
        'Desert Hides',
        1,
        1,
        'Ostrich Beaks',
        1,
        1,
        'Ostrich Eggs',
        1,
        3,
        NULL,
        NULL,
        NULL,
        'Gazelle',
        'Desert Hides',
        1,
        3,
        'Gazelle Horns',
        2,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        22,
        'Hunt Desert Critters Tier 2',
        NULL,
        NULL,
        90,
        68,
        'Monitor',
        'Desert Hides',
        1,
        2,
        'Monitor Scales',
        1,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Ostrich',
        'Desert Hides',
        1,
        1,
        'Ostrich Beaks',
        1,
        1,
        'Ostrich Eggs',
        1,
        3,
        NULL,
        NULL,
        NULL,
        'Gazelle',
        'Desert Hides',
        1,
        3,
        'Gazelle Horns',
        2,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        23,
        'Immortal Tower Courtyard',
        NULL,
        NULL,
        95,
        68,
        'Gorgon',
        'Gorgon Essences',
        1,
        1,
        'Alluring Fabric',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Manticore',
        'Golden Threads',
        1,
        2,
        'Alluring Fabric',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Griffin',
        'Griffin Feathers',
        1,
        3,
        'Divine Marks',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Harpy',
        'Golden Threads',
        1,
        2,
        'Alluring Fabric',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        24,
        'Immortal Tower',
        NULL,
        NULL,
        105,
        72,
        'Medusa',
        'Divine Shards',
        1,
        1,
        'Medusas Eyes',
        1,
        1,
        'Coral Hilts',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Zahhak',
        'Divine Shards',
        1,
        1,
        'Dragon Bones',
        1,
        1,
        'Golden Bows',
        1,
        1,
        NULL,
        NULL,
        NULL,
        'Raynore',
        'Divine Shards',
        1,
        1,
        'Alluring Chords',
        1,
        1,
        'Wicked Staves',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        25,
        'Hunt Big Game Tier 1',
        NULL,
        NULL,
        100,
        78,
        'Nilgiri Tahr',
        'Wild Meat',
        1,
        2,
        'Deccan Hides',
        1,
        2,
        'Tahr Horns',
        1,
        2,
        NULL,
        NULL,
        NULL,
        'Nilgiri Langur',
        'Deccan Hides',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Blackbuck',
        'Wild Meat',
        1,
        3,
        'Deccan Hides',
        1,
        3,
        'Blackbuck Horns',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        26,
        'Hunt Big Game Tier 2',
        NULL,
        NULL,
        110,
        88,
        'Nilgiri Langur',
        'Deccan Hides',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Blackbuck',
        'Wild Meat',
        1,
        3,
        'Deccan Hides',
        1,
        3,
        'Blackbuck Horns',
        1,
        2,
        NULL,
        NULL,
        NULL,
        'Elephant',
        'Wild Meat',
        2,
        4,
        'Deccan Hides',
        2,
        4,
        'Ivory',
        1,
        2,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        27,
        'Spirit Cave',
        NULL,
        NULL,
        115,
        88,
        'Danavas',
        'Primordial Water',
        1,
        2,
        'Demonic Fabric',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Naga',
        'Naga Scales',
        1,
        2,
        'Demonic Fabric',
        1,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Gajasimha',
        'Guard Insignias',
        1,
        1,
        'Alabaster',
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    )